### ISSUE TITLE
Can't Backup Megadeth Table

### ISSUE THREAD

**Issue by gonzonia** [mmattner/vPinBackupManagerApp#1]
I can't backup the Megadeth table, presumably because it's too large. I get this error when I try. I couldn't find any way to enable "UseZip64WhenSaving"
 

<img width="713" alt="Screenshot 2024-02-25 at 9 57 33 AM" src="https://github.com/mmattner/vPinBackupManagerApp/assets/36857621/0f1547d0-29b2-4735-b413-f7be33b56cc6">

**Comment by mmattner** [comment]
This issue is being rolled into version 2.1 of the application currently in testing.
